# Generated by Django 6.0 on 2025-12-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FicheSuivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cours', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('duree', models.DurationField(blank=True, editable=False)),
                ('salle', models.CharField(blank=True, max_length=50)),
                ('type_seance', models.CharField(choices=[('CM', 'Cours Magistral'), ('TD', 'Travaux Dirigés'), ('TP', 'Travaux Pratiques')], max_length=2)),
                ('titre_chapitre', models.CharField(max_length=255)),
                ('contenu_aborde', models.TextField()),
                ('statut', models.CharField(choices=[('SOUMISE', 'Soumise'), ('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée')], default='SOUMISE', max_length=10)),
                ('motif_refus', models.TextField(blank=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_cours', '-heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='UniteEnseignement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ue', models.CharField(max_length=20, unique=True, verbose_name="Code de l'UE")),
                ('libelle_ue', models.CharField(max_length=255, verbose_name="Libellé de l'UE")),
                ('semestre', models.PositiveSmallIntegerField(verbose_name='Semestre')),
            ],
            options={
                'verbose_name': "Unité d'Enseignement",
                'verbose_name_plural': "Unités d'Enseignement",
                'ordering': ['code_ue'],
            },
        ),
    ]
