# Generated by Django 6.0 on 2025-12-29 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('teaching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fichesuivi',
            name='delegue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_soumises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fichesuivi',
            name='enseignant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_a_valider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uniteenseignement',
            name='enseignants',
            field=models.ManyToManyField(blank=True, related_name='ues_enseignees', to=settings.AUTH_USER_MODEL, verbose_name='Enseignants'),
        ),
        migrations.AddField(
            model_name='uniteenseignement',
            name='niveaux',
            field=models.ManyToManyField(blank=True, related_name='programme_ues', to='academic.niveau', verbose_name='Niveaux concernés'),
        ),
        migrations.AddField(
            model_name='fichesuivi',
            name='ue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiches', to='teaching.uniteenseignement'),
        ),
    ]
