# Generated by Django 6.0 on 2026-02-24 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_add_annee_semestre_historique'),
        ('teaching', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichesuivi',
            name='semestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_suivi', to='academic.semestre', verbose_name='Semestre'),
        ),
        migrations.AddField(
            model_name='uniteenseignement',
            name='semestre_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unites_enseignement', to='academic.semestre', verbose_name='Semestre (annee)'),
        ),
        migrations.AlterField(
            model_name='uniteenseignement',
            name='code_ue',
            field=models.CharField(max_length=20, verbose_name="Code de l'UE"),
        ),
        migrations.AlterUniqueTogether(
            name='uniteenseignement',
            unique_together={('code_ue', 'semestre_obj')},
        ),
    ]
