# Generated by Django 6.0 on 2026-02-24 01:12

from django.db import migrations
from datetime import date


def populate_semestres(apps, schema_editor):
    """Creer une annee academique par defaut et lier les donnees existantes."""
    AnneeAcademique = apps.get_model('academic', 'AnneeAcademique')
    Semestre = apps.get_model('academic', 'Semestre')
    UE = apps.get_model('teaching', 'UniteEnseignement')
    FicheSuivi = apps.get_model('teaching', 'FicheSuivi')
    Departement = apps.get_model('academic', 'Departement')
    Historique = apps.get_model('academic', 'HistoriqueChefDepartement')

    # Ne rien faire si la base est vide
    if not UE.objects.exists() and not FicheSuivi.objects.exists() and not Departement.objects.exists():
        return

    # Creer l'annee academique par defaut
    annee, _ = AnneeAcademique.objects.get_or_create(
        libelle='2025-2026',
        defaults={'est_active': True, 'est_configuree': True}
    )

    s1, _ = Semestre.objects.get_or_create(
        annee_academique=annee, numero=1,
        defaults={
            'date_debut': date(2025, 9, 15),
            'date_fin': date(2026, 1, 31),
            'est_actif': False,
        }
    )
    s2, _ = Semestre.objects.get_or_create(
        annee_academique=annee, numero=2,
        defaults={
            'date_debut': date(2026, 2, 1),
            'date_fin': date(2026, 6, 30),
            'est_actif': True,
        }
    )

    # Lier les UEs existantes au bon semestre
    UE.objects.filter(semestre=1, semestre_obj__isnull=True).update(semestre_obj=s1)
    UE.objects.filter(semestre=2, semestre_obj__isnull=True).update(semestre_obj=s2)
    # UEs avec d'autres numeros de semestre → S1 par defaut
    UE.objects.filter(semestre_obj__isnull=True).update(semestre_obj=s1)

    # Lier les fiches au semestre de leur UE
    for fiche in FicheSuivi.objects.select_related('ue').filter(semestre__isnull=True):
        if fiche.ue and fiche.ue.semestre_obj_id:
            FicheSuivi.objects.filter(pk=fiche.pk).update(semestre_id=fiche.ue.semestre_obj_id)

    # Creer historique pour les chefs existants
    today = date.today()
    for dept in Departement.objects.filter(chef_departement__isnull=False):
        Historique.objects.get_or_create(
            departement=dept,
            utilisateur_id=dept.chef_departement_id,
            annee_academique=annee,
            defaults={'date_debut': today}
        )


def reverse_populate(apps, schema_editor):
    """Nettoyage en cas de rollback."""
    AnneeAcademique = apps.get_model('academic', 'AnneeAcademique')
    AnneeAcademique.objects.filter(libelle='2025-2026').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0003_add_semestre_fk'),
        ('academic', '0003_add_annee_semestre_historique'),
    ]

    operations = [
        migrations.RunPython(populate_semestres, reverse_populate),
    ]
