# Generated by Django 6.0 on 2026-03-17 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_create_salle_model'),
        ('teaching', '0005_migrate_salle_to_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], verbose_name='Jour de la semaine')),
                ('heure_debut', models.TimeField(verbose_name='Heure de debut')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('type_seance', models.CharField(default='CM', max_length=2, verbose_name='Type de seance')),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings_cours', to='academic.semestre', verbose_name='Semestre')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings', to='teaching.uniteenseignement', verbose_name="Unite d'enseignement")),
            ],
            options={
                'verbose_name': 'Planning de cours',
                'verbose_name_plural': 'Plannings de cours',
                'ordering': ['jour_semaine', 'heure_debut'],
                'unique_together': {('ue', 'semestre', 'jour_semaine', 'heure_debut')},
            },
        ),
    ]
