# Generated by Django 6.0 on 2026-03-30 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_remove_salle_batiment_remove_salle_capacite'),
        ('teaching', '0006_planningcours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fichesuivi',
            index=models.Index(fields=['statut'], name='idx_fiche_statut'),
        ),
        migrations.AddIndex(
            model_name='fichesuivi',
            index=models.Index(fields=['date_cours'], name='idx_fiche_date'),
        ),
        migrations.AddIndex(
            model_name='fichesuivi',
            index=models.Index(fields=['statut', 'date_cours'], name='idx_fiche_statut_date'),
        ),
        migrations.AddIndex(
            model_name='fichesuivi',
            index=models.Index(fields=['enseignant', 'statut'], name='idx_fiche_enseignant_statut'),
        ),
        migrations.AddIndex(
            model_name='fichesuivi',
            index=models.Index(fields=['delegue', 'statut'], name='idx_fiche_delegue_statut'),
        ),
    ]
