# Generated by Django 6.0 on 2026-01-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnseignantWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="L'adresse email institutionnelle de l'enseignant qui a le droit de créer un compte.", max_length=254, unique=True, verbose_name="Email de l'enseignant autorisé")),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email Enseignant Autorisé',
                'verbose_name_plural': 'Emails Enseignants Autorisés',
                'ordering': ['email'],
            },
        ),
    ]
