# Generated by Django 6.0 on 2026-01-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_enseignantwhitelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Token de l'appareil pour les notifs"),
        ),
    ]
