# Generated by Django 6.0 on 2026-02-08 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_utilisateur_fcm_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnseignantWhitelist',
        ),
    ]
