# Generated by Django 6.0 on 2026-02-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_enseignant_whitelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='auth_provider',
            field=models.CharField(choices=[('password', 'Mot de passe'), ('google', 'Google')], default='password', max_length=20, verbose_name="Methode d'authentification"),
        ),
    ]
