# Generated by Django 6.0 on 2026-03-04 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_create_salle_model'),
        ('users', '0006_add_auth_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email autorisé')),
                ('role_type', models.CharField(choices=[('ENSEIGNANT', 'Enseignant'), ('DELEGUE', 'Délégué')], max_length=20, verbose_name='Type de rôle')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_whitelistes', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_whitelist', to='academic.departement', verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Email Autorisé',
                'verbose_name_plural': 'Emails Autorisés',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
