# Generated by Django 6.0 on 2026-03-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('FICHE_SOUMISE', 'Fiche soumise'), ('FICHE_VALIDEE', 'Fiche validee'), ('FICHE_REFUSEE', 'Fiche refusee'), ('FICHE_RESOUMISE', 'Fiche resoumise'), ('COMPTE_APPROUVE', 'Compte approuve'), ('ALERTE_CHEF', 'Alerte du chef'), ('RAPPEL_ENSEIGNANT', 'Rappel enseignant'), ('RAPPEL_AUTO', 'Rappel automatique'), ('RAPPEL_FICHE', 'Rappel fiche manquante')], max_length=30),
        ),
    ]
