# Generated by Django 6.0 on 2025-12-29 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='chef_departement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departement_gere', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departement',
            name='faculte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='academic.faculte'),
        ),
        migrations.AddField(
            model_name='filiere',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='academic.departement'),
        ),
        migrations.AddField(
            model_name='niveau',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='academic.filiere'),
        ),
        migrations.AlterUniqueTogether(
            name='departement',
            unique_together={('nom_departement', 'faculte')},
        ),
        migrations.AlterUniqueTogether(
            name='filiere',
            unique_together={('nom_filiere', 'departement')},
        ),
        migrations.AlterUniqueTogether(
            name='niveau',
            unique_together={('nom_niveau', 'filiere')},
        ),
    ]
