# Generated by Django 6.0 on 2026-02-24 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Format: YYYY-YYYY (ex: 2025-2026)', max_length=9, unique=True, verbose_name='Annee academique')),
                ('est_active', models.BooleanField(default=False, verbose_name='Annee active')),
                ('est_configuree', models.BooleanField(default=False, verbose_name='Configuration terminee')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Annee Academique',
                'verbose_name_plural': 'Annees Academiques',
                'ordering': ['-libelle'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueChefDepartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chefs_historique', to='academic.anneeacademique')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_chefs', to='academic.departement')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_chefs_departements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique Chef de Departement',
                'verbose_name_plural': 'Historiques Chefs de Departement',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Numero du semestre')),
                ('date_debut', models.DateField(verbose_name='Date de debut')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('est_actif', models.BooleanField(default=False, verbose_name='Semestre actif')),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestres', to='academic.anneeacademique')),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
                'ordering': ['annee_academique', 'numero'],
                'unique_together': {('annee_academique', 'numero')},
            },
        ),
    ]
