# Generated by Django 6.0 on 2026-03-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_add_annee_semestre_historique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_salle', models.CharField(max_length=100, unique=True, verbose_name='Nom de la salle')),
                ('capacite', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacite')),
                ('batiment', models.CharField(blank=True, max_length=100, verbose_name='Batiment')),
                ('est_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['nom_salle'],
            },
        ),
    ]
